steps:

  - task: UseDotNet@2
    displayName: Install .NET 7 SDK
    inputs:
      version: 7.x

  - task: UseDotNet@2
    displayName: Install .NET 6 SDK # Mandatory for the creator tool
    inputs:
      version: 6.x