pool:
  vmImage: "windows-latest"

parameters:
  - name: env
    type: string
    default: DEV
    values:
      - DEV
      - QA

variables:
  - ${{ if or(eq(parameters['env'], 'QA'), eq(variables['Build.SourceBranchName'], 'master'))}}: 
      group: "apim-qa"
    ${{ else }}:
      group: "apim-dev"
  - ${{ if or(eq(parameters['env'], 'QA'), eq(variables['Build.SourceBranchName'], 'master'))}}:
      group: "api-qa"
    ${{ else }}:
      group: "api-dev"
  # - name: SERVICE_CONNECTION_NAME_GITHUB
  #   value: github-service-conn
  - name: System.Debug
    value: false
  - name: buildConfiguration
    value: Release

trigger:
  branches:
    include:
      - master
      - dev
  # paths:
  #   include:
  #     - DZI.B2B.Azure.API/*
    
resources:
  repositories:
    - repository: Creator
      type: github
      # endpoint: $(SERVICE_CONNECTION_NAME_GITHUB) --> not working
      endpoint: "github-service-conn"
      name: Azure/azure-api-management-devops-resource-kit #https://github.com/Azure/azure-api-management-devops-resource-kit.git


stages:
  - template:  Templates/deploy-api.stages.template.yaml
    parameters:
      deployapi_stage: deployapi_stage
  
  - stage: createarm_stage
    displayName: Create ARM Templates
    dependsOn: deployapi_stage
    condition: succeeded()  
    
    jobs:
    - job: create_arm_job
      displayName: Create ARM templates and update TemplateSpecs
      steps:
        - checkout: self
        - checkout: Creator

        - template: Templates/prepare-environment.tasks.template.yaml

        - task: DotNetCoreCLI@2
          displayName: "Build APIM Resource Kit Tool (Creator)"
          inputs:
            command: "build"
            projects: "azure-api-management-devops-resource-kit/**/*.sln"
            arguments: --configuration $(buildConfiguration) --output $(Build.SourcesDirectory)/$(projectName)/$(Path_CreatorTool)
      
        - task: PowerShell@2
          displayName: Check Build.SourcesDirectory
          inputs:
            targetType: 'inline'
            script: |
              Get-ChildItem -path $(Build.SourcesDirectory) -depth 2
              
        - template: Templates/create-arm-templates.tasks.template.yaml

        - task: AzureResourceGroupDeployment@2
          displayName: Deploy APIM to Azure
          inputs:
            azureSubscription: $(SERVICE_CONNECTION_NAME)
            location: $(LOCATION)
            resourceGroupName: $(RG)
            action: "Create Or Update Resource Group"
            templateLocation: "Linked artifact"
            csmFile: $(Build.SourcesDirectory)/$(projectName)/$(ArmMasterTemplate)
            csmParametersFile: $(Build.SourcesDirectory)/$(projectName)/$(ArmParameters)
            deploymentMode: "Incremental" # 'Incremental' | 'Complete' | 'Validation'. Required. Deployment mode. Default: Incremental.
  
  - stage: deployapim_stage
    displayName: Deploy APIM
    dependsOn: createarm_stage
    condition: succeeded()

    jobs:
      - deployment:
        environment: $(ENVIRONMENT)
        displayName: ARM Template Deployment
        strategy:
          runOnce:
            deploy:
              steps:
                - checkout: self
                - task: AzureResourceGroupDeployment@2
                  displayName: ARM Template Deployment
                  inputs:
                    azureSubscription: $(SERVICE_CONNECTION_NAME)
                    location: $(LOCATION)
                    resourceGroupName: $(RG)
                    action: "Create Or Update Resource Group"
                    templateLocation: "Linked artifact"
                    csmFile: $(Build.SourcesDirectory)/$(ArmMasterTemplate)
                    csmParametersFile: $(Build.SourcesDirectory)/$(ArmParameters)
                    deploymentMode: "Incremental"

  - stage: createpr_stage
    displayName: PR for ARMTemplates
    dependsOn: deployapim_stage
    condition: succeeded()  
    
    jobs:
    - job:
      displayName: Create Pull Request
      steps:
        - template: Templates/create-pull-request.tasks.template.yaml